Use user agent "Wget" instead of SELF_USER_AGENT
GregThib/ttrss-tumblr-gdpr pull request #9
Opened 2018-10-12 20:21 UTC by XelaRellum

This change is based on an old version of the plugin as this was the version in my production system. I have tried updating to HEAD but changing from "googlebot" to "Wget" didn't seem to do the trick there.

2018-10-15 21:32 UTC, Zottelchen commented
Already outdated, as well as apparently a  patch for an old version (1.2).

2018-10-15 22:42 UTC, XelaRellum commented
I know it's outdated. But works for me and maybe somebody else too.

Am 15. Oktober 2018 23:32:49 MESZ schrieb Zottelchen <notifications@github.com>:
>Already outdated, as well as apparently a  patch for an old version
>(1.2). 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GregThib/ttrss-tumblr-gdpr/pull/9#issuecomment-430021395

2018-10-16 13:21 UTC, Zottelchen commented
Thats odd, since tumblr blocks wget UA as well now. 
Currently working UAs are:

- Mozilla/5.0 (compatible; Baiduspider; +http://www.baidu.com/search/spider.html)
- facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)

2018-10-17 09:08 UTC, GregThib requested changes
As @Zottelchen said, Wget doesn't work either, so you have to change for one of:
- Mozilla/5.0 (compatible; Baiduspider; +http://www.baidu.com/search/spider.html)
- facebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)

After that I'll pull the request, but support for v1.* is now discontinued.

2019-10-16 21:18 UTC, closed without merging